name: 'dbt_currency_exchange_rates'
version: '1.0.0'
config-version: 2

profile: 'dbt_currency_exchange_rates'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_currency_exchange_rates:
    schema: base

